### ISSUE TITLE
portfolioList is null

### ISSUE THREAD

**Issue by JScheire** [RiyaTayal20/SEP_SMFLSpring2021#99]
Promise does not resolve initially, leaving portfolioList null. This appears to not affect the functionality but is cluttering the console.

**Comment by avidlaud** [comment]
```
TypeError: Cannot read property 'portfolioList' of null
    at getPortfolioHoldings (/home/jscheire/Documents/Projects/SEP_SMFLSpring2021/app/services/league/controllers/leagueController.js:141:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async exports.getPortfolioNews (/home/jscheire/Documents/Projects/SEP_SMFLSpring2021/app/services/league/controllers/leagueController.js:441:35)
```
